### ISSUE TITLE
function not yet c-callable

### ISSUE THREAD

**Issue by matthieugomez** [WizardMac/DataRead.jl#6]
When I try to open a file, I get (on julia 0.3.10 and 0.4)

```
ERROR: cfunction: no method exactly matched the required type signature (function not yet c-callable)
 in read_data_file at /Users/Matthieu/.julia/v0.4/DataRead/src/DataRead.jl:107
```
The line `l107` corresponds to
```julia
    var_fxn = cfunction(handle_variable, Cint, 
        (Cint, Ptr{Int8}, Ptr{Int8}, Ptr{Int8}, Ptr{Int8}, Cint, Csize_t, Ptr{Void}))
```
Looking at the definition for `handle_variable`
```julia
handle_variable(index::Cint, name::Ptr{Int8}, format::Ptr{Int8}, label::Ptr{Int8},
    value_labels::Ptr{Int8}, data_type::Cint, ctx_ptr::Ptr{Void})
```
Does this error come from the `Csize_t` argument?

**Comment by matthieugomez** [comment]
Also, Parser should be of type Ptr{Void} while bytestring(filename) should be of type Ptr{Int8}, no? https://github.com/WizardMac/DataRead.jl/blob/master/src/DataRead.jl#L123

When doing these changes, the function `readstat_parse_dta` seems to be called but I obtain a segfault error.

**Comment by pnvolkmar** [comment]
Having this same problem on Julia 0.3.5. Anyone have any luck?

**Comment by matthieugomez** [comment]
Solved now.
